// ============================================
// VIDEO TEMPLATE LIBRARY
// Each template has a preset for every property
// ============================================
const TEMPLATES = {
    memorial: {
        name: '🕊️ Memorial',
        description: 'In Loving Memory',
        aspectRatio: '1920x1080',
        bgType: 'gradient',
        bgColor1: '#2e2010',
        bgColor2: '#0a0806',
        titleFont: "'Playfair Display', serif",
        titleColor: '#d4af37',
        captionFont: "'Georgia', serif",
        captionColor: '#ffffff',
        highlightColor: '#d4af37',
        captionSize: 42,
        captionStyle: 'box',
        captionAnimation: 'fade',
        captionPosition: 'bottom',
        showTitle: true,
        showSubtitle: true,
        showBadge: false,
        showVisualizer: false,
        showProgress: true,
        title: 'In Loving Memory',
        subtitle: 'Forever In Our Hearts'
    },

    karaoke: {
        name: '🎤 Karaoke Lyrics',
        description: 'Music video with word highlighting',
        aspectRatio: '1920x1080',
        bgType: 'gradient',
        bgColor1: '#0f0c29',
        bgColor2: '#302b63',
        titleFont: "'Bebas Neue', sans-serif",
        titleColor: '#ffffff',
        captionFont: "'Poppins', sans-serif",
        captionColor: '#ffffff',
        highlightColor: '#ffe600',
        captionSize: 56,
        captionStyle: 'glow',
        captionAnimation: 'karaoke',
        captionPosition: 'center',
        showTitle: true,
        showSubtitle: false,
        showBadge: false,
        showVisualizer: true,
        showProgress: true,
        title: 'Song Title',
        subtitle: 'Artist Name'
    },

    tiktok: {
        name: '📱 TikTok / Reels',
        description: 'Vertical short-form',
        aspectRatio: '1080x1920',
        bgType: 'gradient',
        bgColor1: '#ff0080',
        bgColor2: '#7928ca',
        titleFont: "'Montserrat', sans-serif",
        titleColor: '#ffffff',
        captionFont: "'Montserrat', sans-serif",
        captionColor: '#ffffff',
        highlightColor: '#00ff88',
        captionSize: 62,
        captionStyle: 'outline',
        captionAnimation: 'popup',
        captionPosition: 'center',
        showTitle: false,
        showSubtitle: false,
        showBadge: true,
        showVisualizer: false,
        showProgress: false,
        title: '',
        subtitle: '',
        badge: '@yourhandle'
    },

    podcast: {
        name: '🎙️ Podcast Clip',
        description: 'Audio quote with waveform',
        aspectRatio: '1080x1080',
        bgType: 'solid',
        bgSolid: '#1a1a2e',
        bgColor1: '#1a1a2e',
        bgColor2: '#16213e',
        titleFont: "'Inter', sans-serif",
        titleColor: '#00d9ff',
        captionFont: "'Inter', sans-serif",
        captionColor: '#ffffff',
        highlightColor: '#00d9ff',
        captionSize: 44,
        captionStyle: 'minimal',
        captionAnimation: 'typewriter',
        captionPosition: 'center',
        showTitle: true,
        showSubtitle: true,
        showBadge: true,
        showVisualizer: true,
        showProgress: true,
        title: 'The Podcast',
        subtitle: 'Episode Highlight',
        badge: '@podcastname'
    },

    story: {
        name: '📖 Storytelling',
        description: 'Audiobook / narration',
        aspectRatio: '1920x1080',
        bgType: 'gradient',
        bgColor1: '#3a1c71',
        bgColor2: '#d76d77',
        titleFont: "'Playfair Display', serif",
        titleColor: '#ffffff',
        captionFont: "'Georgia', serif",
        captionColor: '#ffffff',
        highlightColor: '#ffd700',
        captionSize: 40,
        captionStyle: 'shadow',
        captionAnimation: 'fade',
        captionPosition: 'bottom',
        showTitle: true,
        showSubtitle: true,
        showBadge: false,
        showVisualizer: false,
        showProgress: true,
        title: 'Chapter One',
        subtitle: 'A Story Told'
    },

    education: {
        name: '🎓 Educational',
        description: 'Tutorial / quote video',
        aspectRatio: '1920x1080',
        bgType: 'gradient',
        bgColor1: '#0093E9',
        bgColor2: '#80D0C7',
        titleFont: "'Montserrat', sans-serif",
        titleColor: '#ffffff',
        captionFont: "'Poppins', sans-serif",
        captionColor: '#ffffff',
        highlightColor: '#ffeb3b',
        captionSize: 44,
        captionStyle: 'box',
        captionAnimation: 'slideup',
        captionPosition: 'bottom',
        showTitle: true,
        showSubtitle: true,
        showBadge: true,
        showVisualizer: false,
        showProgress: true,
        title: 'Lesson 1',
        subtitle: 'Learn Something New'
    },

    sermon: {
        name: '✝️ Sermon / Faith',
        description: 'Bible verse or spiritual',
        aspectRatio: '1920x1080',
        bgType: 'gradient',
        bgColor1: '#141e30',
        bgColor2: '#243b55',
        titleFont: "'Playfair Display', serif",
        titleColor: '#ffd700',
        captionFont: "'Georgia', serif",
        captionColor: '#ffffff',
        highlightColor: '#ffd700',
        captionSize: 46,
        captionStyle: 'shadow',
        captionAnimation: 'fade',
        captionPosition: 'center',
        showTitle: true,
        showSubtitle: true,
        showBadge: false,
        showVisualizer: false,
        showProgress: true,
        title: 'Scripture',
        subtitle: 'Word of God'
    },

    blank: {
        name: '🎨 Blank Canvas',
        description: 'Start from scratch',
        aspectRatio: '1920x1080',
        bgType: 'gradient',
        bgColor1: '#667eea',
        bgColor2: '#764ba2',
        titleFont: "'Poppins', sans-serif",
        titleColor: '#ffffff',
        captionFont: "'Poppins', sans-serif",
        captionColor: '#ffffff',
        highlightColor: '#ffe600',
        captionSize: 42,
        captionStyle: 'box',
        captionAnimation: 'fade',
        captionPosition: 'bottom',
        showTitle: true,
        showSubtitle: true,
        showBadge: false,
        showVisualizer: false,
        showProgress: true,
        title: 'Your Title',
        subtitle: 'Your Subtitle'
    }
};
